server:
  port: 9007
spring:
  application:
    name: tensquare-search
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9200
      repositories:
        enable: true    #是否开启本地缓存
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
   prefer-ip-address: true
