server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
   prefer-ip-address: true
