server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_user?useUnicode=true&characterEncoding=UTF8
    username: root
    password: gaochaojie
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
  redis:
    host: 127.0.0.1
jwt:
  config:
     key: itcast
     ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
   prefer-ip-address: true
